
// this file is partially generated by tools
// do not change the layout

var THREE = require("three");

module.exports =
{
"general":
{
	url: "media/general_atlas.png",
	width: 1558,
	height: 878,
	filter: THREE.LinearFilter,
	sprites:
	{
	"balloon":[1281,342,60,60],
	"builder_guy":[1211,556,124,288],
	"cardboard":[1281,403,60,60],
	"cardboardbox":[1020,727,60,60],
	"crystal":[545,394,281,283],
	"door":[827,394,256,256],
	"grad_circle":[888,804,64,64],
	"grad_r":[953,804,64,64],
	"heaven_angel":[1345,0,212,467],
	"heaven_player":[1084,258,196,297],
	"keydoor":[0,0,544,862],
	"lamp":[1020,788,60,60],
	"magnets":[1461,468,60,60],
	"normal_guy_sprite":[1336,468,124,280],
	"outlet":[1281,258,61,83],
	"suit_sprite":[1084,556,126,280],
	"timedevice":[545,0,537,393],
	"timedevice_button1":[746,781,141,93],
	"timedevice_button2":[899,651,137,75],
	"timedevice_button3":[899,727,120,76],
	"timedevice_button4":[746,678,152,102],
	"timedevice_sticky":[1083,0,261,257],
	"wormhole":[545,678,200,200],
	},
},
"heaven":
{
	url: "media/heaven_atlas.png",
	width: 1236,
	height: 357,
	filter: THREE.LinearFilter,
	sprites:
	{
	"heaven_back_glow_25":[0,247,4,110],
	"heaven_platform":[0,0,1235,246],
	},
},
"prison1":
{
	url: "media/prison1_atlas.png",
	width: 710,
	height: 703,
	filter: THREE.LinearFilter,
	sprites:
	{
	"prison1_ff":[0,0,704,703],
	"prison1_floor":[705,0,4,295],
	"prison1_topshadow":[705,296,4,270],
	},
},
"characters":
{
	url: "media/characters_atlas.png",
	width: 742,
	height: 503,
	filter: THREE.LinearFilter,
	sprites:
	{
	"builder":[426,0,158,243],
	"johnson1":[0,0,212,371],
	"normal_guy":[585,0,156,251],
	"player":[213,0,212,371],
	"suit":[426,244,144,259],
	},
},
}
