
// this file is partially generated by tools
// do not change the layout

var THREE = require("three");

module.exports =
{
"general":
{
	url: "media/general_atlas.png",
	width: 1921,
	height: 1528,
	filter: THREE.LinearFilter,
	sprites:
	{
	"balloon":[0,1468,60,60],
	"builder_guy":[1167,1237,124,288],
	"cardboard":[61,1468,60,60],
	"cardboardbox":[779,1458,60,60],
	"cardboardboxlarge":[153,1365,150,150],
	"crystal":[545,896,281,283],
	"grad_circle":[455,1365,64,64],
	"grad_r":[714,1438,64,64],
	"hammer":[840,1458,60,60],
	"heaven_angel":[827,896,212,467],
	"heaven_player":[1685,703,196,297],
	"keydoor":[0,502,544,862],
	"lamp":[901,1458,60,60],
	"lampbig":[1083,502,300,734],
	"lamplarge":[1384,502,300,734],
	"magnets":[962,1448,60,60],
	"moat_full":[0,0,1920,250],
	"moat_hungry":[0,251,1920,250],
	"normal_guy_sprite":[1292,1237,124,280],
	"outlet":[949,1364,61,83],
	"speaker":[304,1365,150,150],
	"suit_sprite":[1040,1237,126,280],
	"timedevice":[545,502,537,393],
	"timedevice_button1":[807,1364,141,93],
	"timedevice_button2":[455,1438,137,75],
	"timedevice_button3":[593,1438,120,76],
	"timedevice_button4":[0,1365,152,102],
	"timedevice_sticky":[545,1180,261,257],
	"wormhole":[1685,502,200,200],
	},
},
"heaven":
{
	url: "media/heaven_atlas.png",
	width: 1236,
	height: 357,
	filter: THREE.LinearFilter,
	sprites:
	{
	"heaven_back_glow_25":[0,247,4,110],
	"heaven_platform":[0,0,1235,246],
	},
},
"prison1":
{
	url: "media/prison1_atlas.png",
	width: 710,
	height: 703,
	filter: THREE.LinearFilter,
	sprites:
	{
	"prison1_ff":[0,0,704,703],
	"prison1_floor":[705,0,4,295],
	"prison1_topshadow":[705,296,4,270],
	},
},
"characters":
{
	url: "media/characters_atlas.png",
	width: 742,
	height: 503,
	filter: THREE.LinearFilter,
	sprites:
	{
	"builder":[426,0,158,243],
	"johnson1":[0,0,212,371],
	"normal_guy":[585,0,156,251],
	"player":[213,0,212,371],
	"suit":[426,244,144,259],
	},
},
}
