
// this file is partially generated by tools
// do not change the layout

var THREE = require("three");

module.exports =
{
"general":
{
	url: "media/general_atlas.png",
	width: 3850,
	height: 1787,
	filter: THREE.LinearFilter,
	sprites:
	{
	"balloon":[451,1704,60,60],
	"brickwall":[981,603,544,862],
	"builder_guy":[3499,1470,124,288],
	"cardboard":[512,1704,60,60],
	"cardboardbox":[573,1704,60,60],
	"cardboardboxlarge":[2829,1257,150,150],
	"cardboardWall":[1921,0,544,862],
	"cardboardWallBroken":[2071,863,544,855],
	"crystal":[1582,502,281,283],
	"grad_circle":[259,1704,64,64],
	"grad_r":[324,1704,64,64],
	"guard":[3154,853,344,800],
	"guardandtiger":[0,502,980,800],
	"hammer":[634,1704,60,60],
	"heaven_angel":[2616,1257,212,467],
	"heaven_player":[1264,1466,196,297],
	"keydoor":[2466,0,544,862],
	"labyrinth_sign":[0,1303,800,400],
	"lamp":[1526,786,60,60],
	"lampbig":[3549,0,300,734],
	"lamplarge":[3549,735,300,734],
	"magnets":[1587,786,60,60],
	"moat_full":[0,0,1920,250],
	"moat_hungry":[0,251,1920,250],
	"normal_guy_sprite":[3624,1470,124,280],
	"outlet":[389,1704,61,83],
	"puddle":[981,502,600,100],
	"speaker":[2829,1408,150,150],
	"steelwall":[3011,0,537,852],
	"suit_sprite":[2980,1257,126,280],
	"timedevice":[2616,863,537,393],
	"timedevice_button1":[1063,1667,141,93],
	"timedevice_button2":[0,1704,137,75],
	"timedevice_button3":[138,1704,120,76],
	"timedevice_button4":[801,1303,152,102],
	"timedevice_sticky":[801,1466,261,257],
	"woodwall":[1526,863,544,862],
	"wormhole":[1063,1466,200,200],
	},
},
"heaven":
{
	url: "media/heaven_atlas.png",
	width: 1236,
	height: 357,
	filter: THREE.LinearFilter,
	sprites:
	{
	"heaven_back_glow_25":[0,247,4,110],
	"heaven_platform":[0,0,1235,246],
	},
},
"prison1":
{
	url: "media/prison1_atlas.png",
	width: 710,
	height: 703,
	filter: THREE.LinearFilter,
	sprites:
	{
	"prison1_ff":[0,0,704,703],
	"prison1_floor":[705,0,4,295],
	"prison1_topshadow":[705,296,4,270],
	},
},
"characters":
{
	url: "media/characters_atlas.png",
	width: 742,
	height: 503,
	filter: THREE.LinearFilter,
	sprites:
	{
	"builder":[426,0,158,243],
	"johnson1":[0,0,212,371],
	"normal_guy":[585,0,156,251],
	"player":[213,0,212,371],
	"suit":[426,244,144,259],
	},
},
}
